version: '3.9'
services:
  api:
    image: akraradets/donut-api:v0.0.1
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./project:/root/project
      - ./data:/root/data
      - ./model:/root/model
      - vscode-server:/root/.vscode-server
    ports:
      - 9001:80
  web:
    image: httpd:2.4.58-bookworm
    volumes:
      - ./web:/usr/local/apache2/htdocs/
    ports:
      - 9000:80
volumes:
  vscode-server: