version: '3.9'
services:
  web:
    # command: pipenv run python manage.py runserver 0.0.0.0:80
    image: akraradets/donut-web:v0.0.1
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./project:/root/project
      - vscode-web:/root/.vscode-server
    ports:
      - 9000:80

volumes:
  vscode-web: